EXAMPLES = CAE-HMI Class-Table

.PHONY: info clean clear all $(EXAMPLES)

info:
	@echo "SPARQL Model Transformation examples"
	@echo "* CAE-HMI"
	@echo "* Class-Table"
	
	
all: $(EXAMPLES)

$(EXAMPLES):
	@$(MAKE) -C $@;
