# Move left graph in WHERE clause

DELETE {
# Delete left graph from INSERT clause
    ?graph_element rdf:first ?graph; rdf:rest ?element_successor.
    ?element_precesor ?p ?graph_element.

# Insert <left> graph in WHERE clause
    ?query sp:where ?where_first_item.
}
INSERT{
# Delete <left> graph from INSERT clause
    ?element_precesor ?p ?element_successor.

# Insert <left> graph in WHERE clause
    ?query sp:where _:l1.
    _:l1 rdf:first ?graph; rdf:rest ?where_first_item.
}
WHERE{
    ?query sp:insertPattern ?insertList;
        sp:where ?where_first_item.
    ?insertList list:member ?graph.
    ?graph a sp:NamedGraph;
        sp:graphNameNode <graph://left>.

    ?graph_element rdf:first ?graph;
        rdf:rest ?element_successor.
    ?element_precesor ?p ?graph_element.
}
